From ubuntu

sudo apt-get update; \
sudo apt-get install -y apt-transport-https && \
sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-3.1

sudo apt-get install -y aspnetcore-runtime-3.1

sudo apt-get install -y dotnet-runtime-3.1

copy ./rabbitmq-labs /app/rabbitmq-labs

ARG appname
cd  rabbitmq-labs/01_Server-named_Queues/$appname/

dotnet run
