version: '3.7'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "mybroker"
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "5672:5672"
      - "15672:15672"
